name: Publish
on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Update release tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "edge"
          force_push_tag: true

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          tag_name: edge
          body: Automated publish from commit ${{ github.sha }}
          files: |
            plantuml.plug.js
            PLUG.md
